### ISSUE TITLE
Question about data_util.py

### ISSUE THREAD

**Issue by HanyuGuo** [vinhkhuc/MemN2N-babi-python#1]
I find that data_util.py ignores comma while parsing babi task. That is, if the answer of a question is s,w(denotes south and west in positional_reasoning), this parser would treat them as a unit. Furthermore, while asking what stuff someone has and the answer would be "milk,pen,hat" or something like that, the parser would treat them as a unit as well. Is that a correct way?

**Comment by vinhkhuc** [comment]
Hi guohanyu123,
Sorry for the late reply. Since MemN2N assumes that each answer is just one word, "s,w" and "milk,pen,hat" should be treated as units.

**Comment by HanyuGuo** [comment]
Thanks for your reply, vinhkhuc. So apart from MemN2N, can I say that adding an RNN decoder for seq2seq output would provide a better performance? I am just wondering.

**Comment by vinhkhuc** [comment]
That's an interesting question. I'm not sure if anyone has tried it before. Also, using grammar tree parser + word embedding may help. 
Besides that, adding gradient noise can improve the accuracy of memory networks: http://arxiv.org/abs/1511.06807.
