### ISSUE TITLE
Error when using BoW encoding not Positional Encoding

### ISSUE THREAD

**Issue by taey16** [vinhkhuc/MemN2N-babi-python#2]
Hi, @vinhkhuc 

We give thanks to your effort.
By using your repo., we start to reproducing the original MemN2N paper.
However, there was an error when using BoW encoding(i.e. use_bow = True in config.py)
In my opinion, following line should be modified such that
`self.data = np.zeros((config.max_words, self.sz, config.bsz), np.float32) # memory.py(92)`
==>
`self.data = np.zeros((config['max_words'], self.sz, config['bsz']), np.float32)`

Please, give us your comments.

taey16

**Comment by vinhkhuc** [comment]
Hi @taey16,
Yes, it's a syntax bug :(. I've committed the fix as you suggested. Sorry for taking so long to fix a tiny bug.

Vinh
