### ISSUE TITLE
Python Memory Error

### ISSUE THREAD

**Issue by ghost** [vinhkhuc/MemN2N-babi-python#3]
i am getting python memory error thrown every time i try to run the code
it loads model successfully and starts reading data,then just throws MemoryError.

here is my traceback
http://prntscr.com/c63scp

could this be beacuse my pc is too weak ?

**Comment by vinhkhuc** [comment]
Hi Zemaan,
Yes, you probably need more RAM to run the demo.

**Comment by ghost** [comment]
and how much would that be approx. ? is there a way to calculate this ?

**Comment by vinhkhuc** [comment]
I've run the demo web app via "python -m demo.qa" and it used up to 1.5Gb on my laptop.

**Comment by ghost** [comment]
is there any way to reduce RAM comsupmtion by script ?  or undoubtedly confirm that is the RAMs fault ? i'd hate buy more ram only find out its been something else. currently i have only 2GB of ram

**Comment by vinhkhuc** [comment]
Looks like you figured out how to run the demo. I'll close this issue. Feel free to reopen it. Thanks.
