### ISSUE TITLE
What does the number of each data line's end mean? Thank you.

### ISSUE THREAD

**Issue by guotong1988** [vinhkhuc/MemN2N-babi-python#6]
@vinhkhuc Thank you.

For Example: 1 4 4 11 8 2 

1 Mary moved to the bathroom.
2 John went to the hallway.
3 Where is Mary?        bathroom        1
4 Daniel went back to the hallway.
5 Sandra moved to the garden.
6 Where is Daniel?      hallway 4
7 John moved to the office.
8 Sandra journeyed to the bathroom.
9 Where is Daniel?      hallway 4
10 Mary moved to the hallway.
11 Daniel travelled to the office.
12 Where is Daniel?     office  11
13 John went back to the garden.
14 John moved to the bedroom.
15 Where is Sandra?     bathroom        8
1 Sandra travelled to the office.
2 Sandra went to the bathroom.
3 Where is Sandra?      bathroom        2

**Comment by guotong1988** [comment]
Oh , it means the line where the answer word is in.

**Comment by vinhkhuc** [comment]
Yeah, that's correct :)
